import { cn } from '@/shared/lib/utils/cn';
import { Footer } from '@/widgets/Footer';
import { Header } from '@/widgets/Header';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const satoshi = localFont({
  src: '../shared/assets/fonts/Satoshi-Variable.ttf',
  display: 'swap',
  variable: '--font-satoshi',
  weight: '400 700',
  style: 'normal',
});

const interfralCF = localFont({
  src: '../shared/assets/fonts/IntegralCF-Bold.woff2',
  display: 'swap',
  variable: '--font-intergralCF-bold',
  weight: '600',
  style: 'normal',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  menu,
}: {
  children: React.ReactNode;
  menu: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(`${satoshi.variable} ${interfralCF.variable}`, {
          'debug-screens': process.env.NODE_ENV === 'development',
        })}>
        <Header />
        {children}
        {menu}
        <Footer />
      </body>
    </html>
  );
}
